# Generated by Django 4.1.7 on 2023-04-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
