# Generated by Django 4.1.7 on 2023-04-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='email_id',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='logintable',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='logintable',
            table='LOGIN',
        ),
    ]
